### ISSUE TITLE
Replace `in` with regex

### ISSUE THREAD

**Issue by BastianZim** [BastianZim/test-labeler#3]
Ref: https://github.com/BastianZim/test-labeler/blob/0be79560c2fc58ab866eafc68abd45114d233689/.github/workflows/add-review-team.yml#L21

This should be a regex and not an `in` check since this currently triggers for python and python-c as well.

The regex could be something like `word  AND NOT -`.

**Comment by carterbox** [comment]
We need to search for something like `'conda-forge/help-python[(\.\!)\n\s]'`? Including the white space, newline, or punctuation at the end implies the end of the tag?

**Comment by carterbox** [comment]
I believe this is solved. Replaced it with 

```javascript
        const regex = new RegExp(team + '[^\-]|' + team + '$');
        let result = regex.test(text);
```

Which reads as "find team with not-minux OR team with line anchor"
